version: '3'
services:
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx01
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ..:/src
  #     - /var/www/upload:/src/upload
  #     - ./nginx:/etc/nginx/conf.d
  #   depends_on:
  #     - web
  web:
    build: .
    command: ./dev_start.sh #bash -c "python django1/manage.py runserver 0.0.0.0:8000 > django.log 2>&1"
    volumes:
      - ..:/src
    ports:
      - "5432:8000"
    # if use nginx depends_on web
    # expose:
    #   - "8000"
    restart: always